packages:
  # all packages in direct subdirs of packages/
  - 'main/*'
  # all packages in subdirs of components/
  - 'web/**'
  - 'common/**'
  # exclude packages that are inside test directories
  # - '!**/test/**'